import { useState } from "react";
import { useMutation } from "@tanstack/react-query";
import { Bug, Github, Mail, UsersRound } from "lucide-react";
import { apiRequest, jsonBody } from "@/lib/api";
import { team } from "@/content/legacy";
import { Button, Card, Field, Input, Select, Textarea, useToast } from "@/components/ui/Ui";
import { PageFrame } from "@/components/shell/AppShell";
import styles from "./Pages.module.css";

export function AboutPage(){const[form,setForm]=useState({name:"",email:"",issueType:"Bug",description:""});const{notify}=useToast();const report=useMutation({mutationFn:()=>apiRequest("/issue-reports",{method:"POST",...jsonBody(form)}),onSuccess:()=>{notify("Issue report sent! Thank you for your feedback.");setForm({name:"",email:"",issueType:"Bug",description:""})}});const set=(k:string,v:string)=>setForm(x=>({...x,[k]:v}));return <PageFrame title="About Our Team" eyebrow="Meet the developers behind IUTverse"><div className={styles.stack}><Card padded><UsersRound size={34} color="var(--accent)"/><h2>IUTverse</h2><p>IUTverse is a dedicated social platform for the IUT community, built to keep campus conversations, academic resources, opportunities and everyday services together.</p></Card><div className={styles.gridCards} style={{padding:0}}>{team.map(person=><Card key={person.name} className={styles.cardContent}><div style={{height:110,display:"grid",placeItems:"center",background:"var(--surface-2)",borderRadius:14}}><span style={{fontSize:36,fontWeight:900}}>{person.name.split(" ").map(x=>x[0]).slice(0,2).join("")}</span></div><h2>{person.name}</h2><p className={styles.meta}>{person.role}</p><p>{person.bio}</p><p className={styles.meta}>{person.skills.join(" · ")}</p><div className={styles.actions}><a href={`mailto:${person.email}`} aria-label={`Email ${person.name}`}><Mail/></a><a href={person.github} target="_blank" rel="noreferrer" aria-label={`${person.name} on GitHub`}><Github/></a></div></Card>)}</div><Card padded><Bug color="var(--warning)"/><h2>Report an Issue</h2><p>Found a problem or have feedback? Send it directly to the IUTverse team.</p><form className={styles.form} onSubmit={e=>{e.preventDefault();report.mutate()}}><div className={styles.formGrid}><Field label="Name"><Input required value={form.name} onChange={e=>set("name",e.target.value)}/></Field><Field label="Email"><Input required type="email" value={form.email} onChange={e=>set("email",e.target.value)}/></Field><Field label="Issue Type"><Select value={form.issueType} onChange={e=>set("issueType",e.target.value)}><option>Bug</option><option>Accessibility</option><option>Content</option><option>Account</option><option>Other</option></Select></Field></div><Field label="Description"><Textarea required value={form.description} onChange={e=>set("description",e.target.value)} placeholder="Please describe the issue in detail…"/></Field>{report.isError&&<p role="alert">{report.error.message}</p>}<Button type="submit" disabled={report.isPending}>{report.isPending?"Sending…":"Submit report"}</Button></form></Card></div></PageFrame>}
