import { useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Cat, Gamepad2, Heart, ImagePlus, MapPin, MessageCircle, PawPrint, Plus, RefreshCw, Send } from "lucide-react";
import { apiPage, apiRequest, jsonBody, mediaUrl } from "@/lib/api";
import type { CatPost } from "@/lib/types";
import { Button, Card, Chip, Dialog, DialogActions, EmptyState, Field, Input, Textarea, useToast } from "@/components/ui/Ui";
import { PageFrame } from "@/components/shell/AppShell";
import { EntityActions } from "@/features/shared/EntityActions";
import { catSections } from "@/content/legacy";
import { dateLabel } from "./pageUtils";
import styles from "./Pages.module.css";

export function CatCornerPage(){const[section,setSection]=useState("Posts");return <PageFrame title="CatCorner" eyebrow="Enjoy your time with campus cats!" tabs={catSections.map(x=><Chip key={x} active={section===x} onClick={()=>setSection(x)}>{x}</Chip>)}>{section==="Posts"&&<CatFeed/>}{section==="Cat Profiles"&&<CatProfiles/>}{section==="Release your Stress"&&<CatBreak/>}{section==="Random Cat Facts"&&<CatFacts/>}{section==="Cat Help Desk"&&<CatQA/>}{section==="Cat Game"&&<CatGame/>}</PageFrame>}

function CatFeed(){const[compose,setCompose]=useState(false);const[filter,setFilter]=useState("All");const posts=useQuery({queryKey:["cat-posts",filter],queryFn:({signal})=>apiPage<CatPost>(`/cat-posts?category=${filter}&page=1&limit=20`,signal)});return <><div className={styles.toolbar}>{["All","Sighting","Photo","Question","Care","Funny"].map(x=><Chip key={x} active={filter===x} onClick={()=>setFilter(x)}>{x}</Chip>)}<Button onClick={()=>setCompose(true)}><Plus size={17}/>Share a cat post</Button></div><div className={styles.stack}>{posts.isError&&<EmptyState title="CatCorner could not load" body={posts.error.message}/>} {posts.data?.data.length===0&&<EmptyState title="No cat posts here yet" body="Share a campus cat moment."/>}{posts.data?.data.map(post=><Card key={post.id} className={styles.post}><div className={styles.author}><span style={{display:"grid",placeItems:"center",width:42,height:42,borderRadius:"50%",background:"var(--campus-soft)"}}><Cat/></span><div className={styles.authorMeta}><strong>{post.user?.displayName||"IUT member"}</strong><span>{dateLabel(post.createdAt)}</span></div><span className={styles.badge}>{post.category||"Cat post"}</span></div><p className={styles.postText}>{post.caption}</p>{post.location&&<p className={styles.meta}><MapPin size={14}/>{post.location}</p>}{mediaUrl(post.imageUrl)&&<img className={styles.postImage} src={mediaUrl(post.imageUrl)} alt="Campus cat"/>}<div className={styles.actions}><Button variant="ghost"><Heart size={17}/>React {post.likeCount||0}</Button><Button variant="ghost"><MessageCircle size={17}/>Reply {post.commentCount||0}</Button><EntityActions kind="cat_post" id={post.id} saved={post.saved} invalidate={["cat-posts"]}/></div></Card>)}</div><CatPostDialog open={compose} onClose={()=>setCompose(false)}/></>}

function CatPostDialog({open,onClose}:{open:boolean;onClose():void}){const[caption,setCaption]=useState("");const[category,setCategory]=useState("Sighting");const[location,setLocation]=useState("");const[file,setFile]=useState<File|null>(null);const cache=useQueryClient();const{notify}=useToast();const create=useMutation({mutationFn:()=>{const body=new FormData();body.append("caption",caption);body.append("category",category);body.append("location",location);if(file)body.append("image",file);return apiRequest("/cat-posts",{method:"POST",body})},onSuccess:()=>{notify("Cat post shared.");void cache.invalidateQueries({queryKey:["cat-posts"]});onClose();}});return <Dialog title="Share a cat post" open={open} onClose={onClose}><div className={styles.form}><Field label="Share a campus cat moment"><Textarea value={caption} onChange={e=>setCaption(e.target.value)}/></Field><div>{["Sighting","Photo","Question","Care","Funny","Update"].map(x=><Chip key={x} active={category===x} onClick={()=>setCategory(x)}>{x}</Chip>)}</div><Field label="Campus location"><Input value={location} onChange={e=>setLocation(e.target.value)}/></Field><label className={styles.file}><ImagePlus/>Image<input type="file" accept="image/*" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><DialogActions><Button variant="secondary" onClick={onClose}>Cancel</Button><Button disabled={!caption.trim()||create.isPending} onClick={()=>create.mutate()}>Post</Button></DialogActions></div></Dialog>}

const cats=[{name:"Jahangir",desc:"Majestic, loves to bask in the sun near the admin building."},{name:"Sylvie",desc:"A gentle campus regular who enjoys quiet corners."},{name:"Robin",desc:"Curious, social, and often seen near the academic building."},{name:"Batman",desc:"A watchful night wanderer with a very serious expression."},{name:"Jerry",desc:"Playful and always ready to inspect a student’s lunch."}];
function CatProfiles(){return <div className={styles.gridCards}>{cats.map(cat=><Card key={cat.name} className={styles.cardContent}><div style={{height:130,display:"grid",placeItems:"center",borderRadius:14,background:"linear-gradient(135deg,var(--campus-soft),var(--accent-soft))"}}><Cat size={54}/></div><h2>{cat.name}</h2><p>{cat.desc}</p><Button variant="secondary"><PawPrint size={17}/>View profile</Button></Card>)}</div>}

const videos=[{title:"Relaxing cat moments",url:"https://www.youtube.com/results?search_query=relaxing+cat+videos"},{title:"Funny cats for a study break",url:"https://www.youtube.com/results?search_query=funny+cat+videos"},{title:"Calm cats and soft music",url:"https://www.youtube.com/results?search_query=calm+cat+music"}];
function CatBreak(){return <div className={styles.stack}><div className={styles.notice}>Take a short break, breathe, and come back to your work refreshed.</div>{videos.map(v=><Card key={v.title} className={styles.cardContent}><h2>{v.title}</h2><p>Opens a curated YouTube search in a new tab.</p><Button onClick={()=>window.open(v.url,"_blank","noopener,noreferrer")}>Watch cat videos</Button></Card>)}</div>}

const facts=["Cats spend around two-thirds of their lives sleeping.","A cat’s nose print is unique, much like a human fingerprint.","Cats use their whiskers to understand whether they can fit through a space.","Slow blinking is often a sign of trust and comfort."];
function CatFacts(){const[index,setIndex]=useState(0);return <div className={styles.stack}><Card padded><Cat size={44} color="var(--campus)"/><h2>Random Cat Fact</h2><p style={{fontSize:20,lineHeight:1.5}}>{facts[index]}</p><Button onClick={()=>setIndex((index+1)%facts.length)}><RefreshCw size={17}/>New fact</Button></Card></div>}

interface Question{id:number;question:string;answers?:{id:number;answer:string}[]}
function CatQA(){const[text,setText]=useState("");const[answers,setAnswers]=useState<Record<number,string>>({});const cache=useQueryClient();const data=useQuery({queryKey:["cat-qa"],queryFn:({signal})=>apiPage<Question>("/cat-qa/questions?page=1&limit=20",signal)});const ask=useMutation({mutationFn:()=>apiRequest("/cat-qa/questions",{method:"POST",...jsonBody({questionText:text})}),onSuccess:()=>{setText("");void cache.invalidateQueries({queryKey:["cat-qa"]})}});const answer=useMutation({mutationFn:({id,text}:{id:number;text:string})=>apiRequest(`/cat-qa/questions/${id}/answers`,{method:"POST",...jsonBody({answerText:text})}),onSuccess:()=>void cache.invalidateQueries({queryKey:["cat-qa"]})});return <div className={styles.stack}><Card padded><h2>Cat Help Desk</h2><div style={{display:"flex",gap:8}}><Input value={text} onChange={e=>setText(e.target.value)} placeholder="e.g. How often should I feed stray cats?"/><Button disabled={!text.trim()} onClick={()=>ask.mutate()}><Send size={17}/>Ask</Button></div></Card>{data.data?.data.map(q=><Card key={q.id} padded><h3>{q.question}</h3>{q.answers?.map(a=><p key={a.id} className={styles.notice}>{a.answer}</p>)}<div style={{display:"flex",gap:8}}><Input value={answers[q.id]||""} onChange={e=>setAnswers(v=>({...v,[q.id]:e.target.value}))} placeholder="Write an answer/advice…"/><Button onClick={()=>answer.mutate({id:q.id,text:answers[q.id]})}>Answer</Button></div></Card>)}</div>}

function CatGame(){const[playing,setPlaying]=useState(false);const[level,setLevel]=useState(1);const[score,setScore]=useState(0);const[lives,setLives]=useState(9);const[target,setTarget]=useState({x:50,y:50});const[pos,setPos]=useState({x:10,y:50});const move=(dx:number,dy:number)=>setPos(p=>{const next={x:Math.max(0,Math.min(90,p.x+dx)),y:Math.max(0,Math.min(85,p.y+dy))};if(Math.hypot(next.x-target.x,next.y-target.y)<12){setScore(s=>s+100*level);setTarget({x:10+Math.random()*75,y:10+Math.random()*70});if(score>=level*300)setLevel(l=>Math.min(5,l+1))}return next});useEffect(()=>{if(!playing)return;const key=(e:KeyboardEvent)=>{const map:Record<string,[number,number]>={ArrowUp:[0,-6],ArrowDown:[0,6],ArrowLeft:[-6,0],ArrowRight:[6,0],w:[0,-6],s:[0,6],a:[-6,0],d:[6,0]};if(map[e.key]){e.preventDefault();move(...map[e.key])}};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key)},[playing,score,level]);return <div className={styles.stack}><Card padded><div className={styles.titleRow}><div><h2>Campus Cat Quest</h2><p>Collect the glowing fish, clear five levels, and protect your nine lives.</p></div><Gamepad2 size={38}/></div><div className={styles.metrics}><span><strong>{score}</strong> score</span><span><strong>{level}</strong> level</span><span><strong>{lives}</strong> lives</span></div><div style={{position:"relative",height:360,marginTop:16,border:"1px solid var(--border)",borderRadius:16,background:"radial-gradient(circle at 50% 50%,#13231d,#08100d)",overflow:"hidden"}}>{playing&&<><button aria-label="Campus cat" style={{position:"absolute",left:`${pos.x}%`,top:`${pos.y}%`,border:0,background:"transparent",fontSize:36}}>🐈</button><span aria-label="Collectible fish" style={{position:"absolute",left:`${target.x}%`,top:`${target.y}%`,fontSize:28}}>🐟</span></>}</div>{!playing?<Button onClick={()=>setPlaying(true)}>Start game</Button>:<><div style={{display:"grid",gridTemplateColumns:"repeat(3,54px)",justifyContent:"center",gap:6,marginTop:12}}><span/><Button iconOnly variant="secondary" aria-label="Move up" onClick={()=>move(0,-6)}>↑</Button><span/><Button iconOnly variant="secondary" aria-label="Move left" onClick={()=>move(-6,0)}>←</Button><Button iconOnly variant="secondary" aria-label="Move down" onClick={()=>move(0,6)}>↓</Button><Button iconOnly variant="secondary" aria-label="Move right" onClick={()=>move(6,0)}>→</Button></div><Button variant="secondary" onClick={()=>{setPlaying(false);setScore(0);setLevel(1);setLives(9);setPos({x:10,y:50})}}>Reset game</Button></>}</Card></div>}
