import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Feather, MessageCircle, Plus, ShieldCheck, Sparkles, ThumbsUp } from "lucide-react";
import { apiPage, apiRequest, jsonBody } from "@/lib/api";
import type { Confession } from "@/lib/types";
import { Button, Card, Chip, Dialog, DialogActions, EmptyState, Field, Input, Textarea, useToast } from "@/components/ui/Ui";
import { PageFrame } from "@/components/shell/AppShell";
import { EntityActions } from "@/features/shared/EntityActions";
import { dateLabel, queryString } from "./pageUtils";
import styles from "./Pages.module.css";

const filters=["Latest","Popular","Polls","Support","Random"];
export function ConfessionsPage(){const[filter,setFilter]=useState("Latest");const[search,setSearch]=useState("");const[compose,setCompose]=useState(false);const data=useQuery({queryKey:["confessions",filter,search],queryFn:({signal})=>apiPage<Confession>(`/confessions${queryString({sort:filter.toLowerCase(),search,limit:20})}`,signal)});return <PageFrame title="Confessions" eyebrow="Private expression, without a profile trail" action={<Button onClick={()=>setCompose(true)}><Plus size={17}/>Write confession</Button>} tabs={filters.map(x=><Chip key={x} active={filter===x} onClick={()=>setFilter(x)}>{x}</Chip>)}><div className={`${styles.notice}`} style={{margin:16}}><ShieldCheck size={20}/><strong>Your identity stays hidden from readers.</strong> Avoid names, student IDs, exact locations, or details that could identify someone.</div><div className={styles.toolbar}><Input className={styles.toolbarGrow} value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search confessions" aria-label="Search confessions"/></div><div className={styles.stack}>{data.isLoading&&<Card padded>Loading confessions…</Card>}{data.isError&&<EmptyState title="Confessions could not load" body={data.error.message}/>} {data.data?.data.length===0&&<EmptyState title="No confessions with this tag yet" body="Write the first one if you have something to share."/>}{data.data?.data.map(item=><ConfessionCard key={item.id} item={item}/>)}</div><ConfessionDialog open={compose} onClose={()=>setCompose(false)}/></PageFrame>}

function ConfessionCard({item}:{item:Confession}){const cache=useQueryClient();const react=useMutation({mutationFn:()=>apiRequest(`/confessions/${item.id}/reactions`,{method:"POST",...jsonBody({reactionType:"relatable"})}),onSuccess:()=>void cache.invalidateQueries({queryKey:["confessions"]})});return <Card className={styles.cardContent}><div className={styles.author}><span style={{width:42,height:42,display:"grid",placeItems:"center",borderRadius:"50%",background:"var(--surface-3)"}}><Feather/></span><div className={styles.authorMeta}><strong>Anonymous</strong><span>{dateLabel(item.createdAt)} · Identity hidden from readers</span></div><span className={styles.badge}>{item.tag}</span></div><p className={styles.postText}>{item.content}</p>{item.poll&&<div><h3>{item.poll.question}</h3>{item.poll.options.map(option=>{const pct=item.poll?.totalVotes?Math.round(option.votes/item.poll.totalVotes*100):0;return <button key={option.id} style={{width:"100%",position:"relative",overflow:"hidden",border:"1px solid var(--border)",borderRadius:10,background:"var(--surface-2)",color:"var(--fg)",padding:10,marginBottom:7,textAlign:"left"}}><span style={{position:"absolute",inset:0,width:`${pct}%`,background:"var(--accent-soft)"}}/><span style={{position:"relative"}}>{option.text} · {pct}%</span></button>})}</div>}<div className={styles.stats}><span>{item.reactionCount||0} reactions</span><span>{item.comments?.length||0} replies</span></div><div className={styles.actions}><Button variant="ghost" onClick={()=>react.mutate()}><ThumbsUp size={17}/>React</Button><Button variant="ghost"><MessageCircle size={17}/>Reply</Button><EntityActions kind="confession" id={item.id} saved={item.saved} invalidate={["confessions"]}/></div></Card>}

function ConfessionDialog({open,onClose}:{open:boolean;onClose():void}){const[draft,setDraft]=useState(()=>localStorage.getItem("iutverse:v2:confession-draft")||"");const[tag,setTag]=useState("Random");const[poll,setPoll]=useState(false);const[pollQuestion,setPollQuestion]=useState("");const[options,setOptions]=useState(["",""]);const[ack,setAck]=useState(false);const cache=useQueryClient();const{notify}=useToast();const create=useMutation({mutationFn:()=>apiRequest("/confessions",{method:"POST",...jsonBody({content:draft,tag,poll:poll?{question:pollQuestion,options:options.filter(Boolean)}:undefined})}),onSuccess:()=>{localStorage.removeItem("iutverse:v2:confession-draft");setDraft("");notify("Confession published anonymously.");void cache.invalidateQueries({queryKey:["confessions"]});onClose();}});const update=(value:string)=>{setDraft(value);localStorage.setItem("iutverse:v2:confession-draft",value)};return <Dialog title="Write a confession" open={open} onClose={onClose}><form className={styles.form} onSubmit={e=>{e.preventDefault();create.mutate();}}><Field label={`Confession (${draft.length}/2000)`}><Textarea required maxLength={2000} value={draft} onChange={e=>update(e.target.value)} placeholder="Share what is on your mind…"/></Field><div style={{display:"flex",flexWrap:"wrap",gap:7}}>{["Academic stress","Campus life","Friendship","Love","Advice","Random","Support"].map(x=><Chip key={x} active={tag===x} onClick={()=>setTag(x)}>{x}</Chip>)}</div><Chip active={poll} onClick={()=>setPoll(v=>!v)}>Toggle poll</Chip>{poll&&<><Field label="Poll question"><Input required value={pollQuestion} onChange={e=>setPollQuestion(e.target.value)}/></Field>{options.map((x,i)=><Field key={i} label={`Poll option ${i+1}`}><Input value={x} onChange={e=>setOptions(v=>v.map((o,n)=>n===i?e.target.value:o))}/></Field>)}{options.length<5&&<Button variant="secondary" onClick={()=>setOptions(v=>[...v,""])}>Add option</Button>}</>}<label className={styles.notice}><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/> I understand this confession cannot be edited later.</label>{create.isError&&<p role="alert">{create.error.message}</p>}<DialogActions><Button variant="secondary" onClick={onClose}>Cancel</Button><Button type="submit" disabled={!draft.trim()||!ack||create.isPending}><Sparkles size={17}/>{create.isPending?"Publishing…":"Publish anonymously"}</Button></DialogActions></form></Dialog>}
