import { useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { CalendarDays, Edit3, MapPin, Plus, Share2, Trash2, UsersRound } from "lucide-react";
import { apiPage, apiRequest, jsonBody, mediaUrl } from "@/lib/api";
import type { EventItem } from "@/lib/types";
import { Button, Card, Chip, Dialog, DialogActions, EmptyState, Field, Input, Select, Textarea, useToast } from "@/components/ui/Ui";
import { PageFrame } from "@/components/shell/AppShell";
import { EntityActions } from "@/features/shared/EntityActions";
import { eventClubs } from "@/content/legacy";
import { useAuth } from "@/features/auth/AuthProvider";
import { queryString } from "./pageUtils";
import styles from "./Pages.module.css";

export function EventsPage(){const[type,setType]=useState("All");const[create,setCreate]=useState(false);const[editing,setEditing]=useState<EventItem|null>(null);const events=useQuery({queryKey:["events",type],queryFn:({signal})=>apiPage<EventItem>(`/events${queryString({type:type==="All"?undefined:type})}`,signal)});return <PageFrame title="Event Hub" eyebrow="Discover and join exciting events happening at IUT" action={<Button onClick={()=>setCreate(true)}><Plus size={17}/>Add Your Event</Button>} tabs={["All","General","Club","Sports","Wishlisted"].map(x=><Chip key={x} active={type===x} onClick={()=>setType(x)}>{x}</Chip>)}><div className={styles.gridCards}>{events.isLoading&&<Card padded>Loading events…</Card>}{events.isError&&<EmptyState title="Event Hub could not load" body={events.error.message}/>} {events.data?.data.length===0&&<EmptyState title="No events found" body="Try adjusting your filters or add an event for the IUT community."/>}{events.data?.data.map(item=><EventCard key={item.id} item={item} onEdit={()=>setEditing(item)}/>)}</div><EventDialog open={create} onClose={()=>setCreate(false)}/><EventDialog open={Boolean(editing)} item={editing||undefined} onClose={()=>setEditing(null)}/></PageFrame>}

function EventCard({item,onEdit}:{item:EventItem;onEdit():void}){const{user}=useAuth();const cache=useQueryClient();const{notify}=useToast();const rsvp=useMutation({mutationFn:()=>apiRequest(`/events/${item.id}/rsvp`,{method:"PUT",...jsonBody({status:item.rsvpStatus?"not_going":"going"})}),onSuccess:()=>{notify(item.rsvpStatus?"Registration removed.":"You are registered.");void cache.invalidateQueries({queryKey:["events"]})}});const remove=useMutation({mutationFn:()=>apiRequest(`/events/${item.id}`,{method:"DELETE"}),onSuccess:()=>{notify("Event deleted.");void cache.invalidateQueries({queryKey:["events"]})}});const image=mediaUrl(item.imageUrl);const owner=item.createdBy?.id===user?.id;return <Card>{image?<img src={image} alt="" style={{height:190,width:"100%",objectFit:"cover"}}/>:<div style={{height:150,display:"grid",placeItems:"center",background:"linear-gradient(135deg,var(--accent-soft),var(--campus-soft))"}}><CalendarDays size={54}/></div>}<div className={styles.cardContent}><span className={styles.badge}>{item.type||"Event"}</span><h2>{item.title}</h2><p>{item.description}</p><p className={styles.meta}><CalendarDays size={14}/>{new Date(item.eventDate).toLocaleString()}</p><p className={styles.meta}><MapPin size={14}/>{item.location}</p>{item.clubName&&<p className={styles.meta}><UsersRound size={14}/>{item.clubName}</p>}<div className={styles.actions}><Button onClick={()=>rsvp.mutate()}>{item.rsvpStatus==="going"?"Registered":"Register Now"}</Button><Button variant="ghost" onClick={()=>void navigator.clipboard.writeText(`${location.origin}/events/${item.id}`).then(()=>notify("Event link copied."))}><Share2 size={17}/>Share</Button>{owner&&<Button variant="ghost" onClick={onEdit}><Edit3 size={17}/>Edit</Button>}{owner&&<Button variant="danger" onClick={()=>remove.mutate()} disabled={remove.isPending}><Trash2 size={17}/>Delete</Button>}<EntityActions kind="event" id={item.id} saved={item.saved} invalidate={["events"]}/></div></div></Card>}

function EventDialog({open,onClose,item}:{open:boolean;onClose():void;item?:EventItem}){
  const[form,setForm]=useState({title:"",type:"General",clubName:"",eventDate:"",location:"",category:"",description:""});const[file,setFile]=useState<File|null>(null);const cache=useQueryClient();const{notify}=useToast();
  useEffect(()=>{if(item)setForm({title:item.title,type:item.type||"General",clubName:item.clubName||"",eventDate:new Date(item.eventDate).toISOString().slice(0,16),location:item.location,category:item.category||"",description:item.description})},[item]);
  const create=useMutation({mutationFn:()=>{const body=new FormData();Object.entries({...form,eventDate:new Date(form.eventDate).toISOString()}).forEach(([key,value])=>value&&body.append(key,value));if(file)body.append("image",file);return apiRequest(item?`/events/${item.id}`:"/events",{method:item?"PUT":"POST",body})},onSuccess:()=>{notify(item?"Event updated.":"Event submitted.");void cache.invalidateQueries({queryKey:["events"]});onClose()}});const set=(k:string,v:string)=>setForm(x=>({...x,[k]:v}));
  return <Dialog title={item?"Edit event":"Add Your Event"} open={open} onClose={onClose}><form className={styles.form} onSubmit={e=>{e.preventDefault();create.mutate()}}><Field label="Event title"><Input required value={form.title} onChange={e=>set("title",e.target.value)}/></Field><div className={styles.formGrid}><Field label="Event type"><Select value={form.type} onChange={e=>set("type",e.target.value)}><option>General</option><option>Club</option><option>Sports</option></Select></Field>{form.type==="Club"&&<Field label="Club name"><Select value={form.clubName} onChange={e=>set("clubName",e.target.value)}><option value="">Select club</option>{eventClubs.map(x=><option key={x}>{x}</option>)}</Select></Field>}<Field label="Date and time"><Input required type="datetime-local" value={form.eventDate} onChange={e=>set("eventDate",e.target.value)}/></Field><Field label="Location"><Input required value={form.location} onChange={e=>set("location",e.target.value)}/></Field><Field label="Category"><Input value={form.category} onChange={e=>set("category",e.target.value)}/></Field></div><Field label="Description"><Textarea required value={form.description} onChange={e=>set("description",e.target.value)}/></Field><label className={styles.file}>Event image<input type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><div className={styles.notice}>Include complete event details. Events are visible after verification where moderation is required.</div>{create.isError&&<p role="alert">{create.error.message}</p>}<DialogActions><Button variant="secondary" onClick={onClose}>Close</Button><Button type="submit" disabled={!form.title||!form.eventDate||!form.location||create.isPending}>{item?"Save changes":"Submit event"}</Button></DialogActions></form></Dialog>
}
