import { useEffect, useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useSearchParams } from "react-router-dom";
import { ArrowLeft, ImagePlus, MessageSquarePlus, Search, Send } from "lucide-react";
import { apiPage, apiRequest } from "@/lib/api";
import { supabase } from "@/lib/supabase";
import type { Conversation, Message, Profile } from "@/lib/types";
import { Avatar, Button, Dialog, DialogActions, EmptyState, Input } from "@/components/ui/Ui";
import { PageFrame } from "@/components/shell/AppShell";
import { useAuth } from "@/features/auth/AuthProvider";
import { dateLabel } from "./pageUtils";
import styles from "./Pages.module.css";

export function MessagesPage(){const[active,setActive]=useState<Conversation|null>(null);const[search,setSearch]=useState("");const[newOpen,setNewOpen]=useState(false);const[params,setParams]=useSearchParams();const list=useQuery({queryKey:["conversations"],queryFn:({signal})=>apiPage<Conversation>("/chat/conversations",signal),refetchInterval:30000});const filtered=useMemo(()=>list.data?.data.filter(c=>(c.otherUser?.displayName||"").toLowerCase().includes(search.toLowerCase()))||[],[list.data,search]);useEffect(()=>{if(params.get("new")==="1")setNewOpen(true);const id=Number(params.get("conversation"));if(id&&list.data?.data.length){const selected=list.data.data.find(item=>item.id===id);if(selected)setActive(selected)}},[list.data,params]);const select=(conversation:Conversation)=>{setActive(conversation);setParams({conversation:String(conversation.id)},{replace:true})};const closeNew=()=>{setNewOpen(false);if(params.get("new"))setParams({}, {replace:true})};return <PageFrame title="Messages" eyebrow="Private conversations" action={<Button onClick={()=>{setNewOpen(true);setParams({new:"1"},{replace:true})}}><MessageSquarePlus size={17}/>New message</Button>}><div className={styles.chat}><section className={`${styles.conversationList} ${active?styles.chatHidden:""}`}><div className={styles.toolbar}><Search size={17}/><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search people or conversations" aria-label="Search conversations"/></div>{list.isError&&<EmptyState title="Messages could not load" body={list.error.message}/>} {filtered.length===0&&!list.isLoading&&<EmptyState title="No conversations found" body="Start a new message with a verified IUT member."/>}{filtered.map(c=><button key={c.id} className={`${styles.conversation} ${active?.id===c.id?styles.conversationActive:""}`} onClick={()=>select(c)}><Avatar name={c.otherUser?.displayName}/><div className={styles.authorMeta}><strong>{c.otherUser?.displayName||"IUT member"}</strong><span>{c.lastMessage||"Start the conversation"}</span></div><small>{dateLabel(c.updatedAt)}</small></button>)}</section><section className={`${styles.chatPane} ${!active?styles.chatHidden:""}`}>{active?<ChatPane conversation={active} onBack={()=>{setActive(null);setParams({}, {replace:true})}}/>:<EmptyState title="Select a conversation" body="Your messages will appear here."/>}</section></div><NewConversation open={newOpen} onClose={closeNew} onStarted={c=>{setActive(c);setNewOpen(false);setParams({conversation:String(c.id)},{replace:true})}}/></PageFrame>}

function ChatPane({conversation,onBack}:{conversation:Conversation;onBack():void}){const{user}=useAuth();const[text,setText]=useState("");const[file,setFile]=useState<File|null>(null);const cache=useQueryClient();const messages=useQuery({queryKey:["messages",conversation.id],queryFn:({signal})=>apiPage<Message>(`/chat/conversations/${conversation.id}/messages?page=1&limit=50`,signal),refetchInterval:10000});useEffect(()=>{const channel=supabase.channel(`conversation:${conversation.id}`).on("postgres_changes",{event:"INSERT",schema:"public",table:"chat_messages",filter:`conversation_id=eq.${conversation.id}`},()=>void cache.invalidateQueries({queryKey:["messages",conversation.id]})).subscribe();return()=>{void supabase.removeChannel(channel)}},[cache,conversation.id]);const send=useMutation({mutationFn:()=>{const body=new FormData();body.append("conversationId",String(conversation.id));body.append("receiverId",conversation.otherUser?.id||"");body.append("content",text);if(file)body.append("attachment",file);return apiRequest("/chat/messages",{method:"POST",body})},onSuccess:()=>{setText("");setFile(null);void cache.invalidateQueries({queryKey:["messages",conversation.id]});void cache.invalidateQueries({queryKey:["conversations"]})}});return <><header className={styles.chatHeader}><Button variant="ghost" iconOnly aria-label="Back to conversations" onClick={onBack}><ArrowLeft/></Button><Avatar name={conversation.otherUser?.displayName}/><div><strong>{conversation.otherUser?.displayName||"IUT member"}</strong><div className={styles.meta}>{conversation.otherUser?.department||"Verified IUT member"}</div></div></header><div className={styles.messages}>{messages.isLoading&&<p>Loading messages…</p>}{messages.data?.data.length===0&&<EmptyState title="Start the conversation" body="Messages are private between verified IUT members."/>}{messages.data?.data.map(m=><div key={m.id} className={`${styles.bubble} ${m.senderId===user?.id?styles.bubbleOwn:""}`}><div>{m.content}</div>{m.attachmentUrl&&<a href={m.attachmentUrl} target="_blank" rel="noreferrer">{m.attachmentName||"Attachment"}</a>}<small style={{display:"block",opacity:.7,marginTop:4}}>{dateLabel(m.sentAt)}</small></div>)}</div><form className={styles.messageForm} onSubmit={e=>{e.preventDefault();send.mutate()}}><label><span className="sr-only">Attach image or file</span><input className="sr-only" type="file" onChange={e=>setFile(e.target.files?.[0]||null)}/><Button variant="ghost" iconOnly aria-label={file?`Attached ${file.name}`:"Attach file"}><ImagePlus/></Button></label><Input value={text} onChange={e=>setText(e.target.value)} placeholder={`Message ${conversation.otherUser?.displayName||"user"}…`}/><Button type="submit" iconOnly aria-label="Send message" disabled={send.isPending||(!text.trim()&&!file)}><Send/></Button></form></>}

function NewConversation({open,onClose,onStarted}:{open:boolean;onClose():void;onStarted(c:Conversation):void}){const[search,setSearch]=useState("");const users=useQuery({queryKey:["user-search",search],queryFn:({signal})=>apiPage<Profile>(`/users/search?q=${encodeURIComponent(search)}`,signal),enabled:search.trim().length>=2});const start=useMutation({mutationFn:(id:string)=>apiRequest<Conversation>("/chat/conversations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({otherUserId:id})}),onSuccess:r=>onStarted(r.data)});return <Dialog title="New message" open={open} onClose={onClose}><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Enter name or email…" autoFocus/>{users.data?.data.map(user=><button key={user.id} className={styles.conversation} onClick={()=>start.mutate(user.id)}><Avatar name={user.displayName}/><div><strong>{user.displayName}</strong><div className={styles.meta}>{user.department}{user.batch?` ${user.batch}`:""}</div></div></button>)}{search.length<2&&<EmptyState title="Find an IUT member" body="Type at least two characters."/>}<DialogActions><Button variant="secondary" onClick={onClose}>Cancel</Button></DialogActions></Dialog>}
