import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Archive, CheckCircle2, ShieldCheck, XCircle } from "lucide-react";
import { apiPage, apiRequest, jsonBody } from "@/lib/api";
import type { ReportItem } from "@/lib/types";
import { Button, Card, Chip, EmptyState } from "@/components/ui/Ui";
import { PageFrame } from "@/components/shell/AppShell";
import styles from "./Pages.module.css";

export function ModerationPage(){const[filter,setFilter]=useState("pending");const cache=useQueryClient();const reports=useQuery({queryKey:["reports",filter],queryFn:({signal})=>apiPage<ReportItem>(`/reports?status=${filter}`,signal)});const update=useMutation({mutationFn:({id,status,action}:{id:number;status:string;action:string})=>apiRequest(`/reports/${id}`,{method:"PATCH",...jsonBody({status,action})}),onSuccess:()=>void cache.invalidateQueries({queryKey:["reports"]})});return <PageFrame title="Content Moderation" eyebrow="Admin and moderator access" tabs={["pending","reviewed","dismissed"].map(x=><Chip key={x} active={filter===x} onClick={()=>setFilter(x)}>{x}</Chip>)}><div className={styles.stack}><div className={styles.notice}><ShieldCheck/>Moderation actions are recorded and authorization is enforced by the server.</div>{reports.isError&&<EmptyState title="Moderation queue unavailable" body={reports.error.message}/>} {reports.data?.data.length===0&&<EmptyState title="No pending reports" body="All reported content in this view has been reviewed."/>}{reports.data?.data.map(report=><Card padded key={report.id}><div className={styles.moderationRow}><div><span className={styles.badge}>{report.entityKind}</span><h2>Report #{report.id}</h2><p>{report.reason}</p>{report.details&&<p className={styles.meta}>{report.details}</p>}</div><div className={styles.actions}><Button onClick={()=>update.mutate({id:report.id,status:"reviewed",action:"approve"})}><CheckCircle2 size={17}/>Restore</Button><Button variant="danger" onClick={()=>update.mutate({id:report.id,status:"reviewed",action:"archive"})}><Archive size={17}/>Archive</Button><Button variant="secondary" onClick={()=>update.mutate({id:report.id,status:"dismissed",action:"dismiss"})}><XCircle size={17}/>Dismiss</Button></div></div></Card>)}</div></PageFrame>}
