import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { BookOpen, Download, ExternalLink, Plus, ThumbsUp } from "lucide-react";
import { apiPage, apiRequest } from "@/lib/api";
import type { Resource } from "@/lib/types";
import { Button, Card, Chip, Dialog, DialogActions, EmptyState, Field, Input, Select, Textarea, useToast } from "@/components/ui/Ui";
import { PageFrame } from "@/components/shell/AppShell";
import { EntityActions } from "@/features/shared/EntityActions";
import { dateLabel, queryString } from "./pageUtils";
import styles from "./Pages.module.css";

const types = ["All", "QUESTION", "NOTE", "BOOK", "OTHER", "CLASS_LECTURE", "PDF", "SLIDES", "LAB_MANUAL", "QUESTION_SOLUTION", "LINK", "VIDEO", "DATASET"];

export function ResourcesPage() {
  const [type, setType] = useState("All"); const [search, setSearch] = useState(""); const [course, setCourse] = useState(""); const [upload, setUpload] = useState(false);
  const resources = useQuery({ queryKey: ["resources", type, search, course], queryFn: ({ signal }) => apiPage<Resource>(`/academic/resources${queryString({ type: type === "All" ? undefined : type, search, courseCode: course })}`, signal) });
  return <PageFrame title="Academic Resource Hub" eyebrow="Learn & Work" action={<Button onClick={() => setUpload(true)}><Plus size={17} />Share resource</Button>} tabs={types.slice(0,8).map(item => <Chip key={item} active={item === type} onClick={() => setType(item)}>{item.replaceAll("_", " ")}</Chip>)}><div className={styles.toolbar}><Input className={styles.toolbarGrow} value={search} onChange={e => setSearch(e.target.value)} placeholder="Search resources…" aria-label="Search resources" /><Input value={course} onChange={e => setCourse(e.target.value)} placeholder="Course code" aria-label="Filter by course code" /></div><div className={styles.stack}>{resources.isLoading && <Card padded>Loading resources…</Card>}{resources.isError && <EmptyState title="Academic Resources could not load" body={resources.error.message} action={<Button onClick={() => void resources.refetch()}>Try again</Button>} />}{resources.data?.data.length === 0 && <EmptyState title="No resources found" body="Clear filters or share the first resource." />}{resources.data?.data.map(resource => <ResourceCard key={resource.id} resource={resource} />)}</div><ResourceDialog open={upload} onClose={() => setUpload(false)} /></PageFrame>;
}

function ResourceCard({ resource }: { resource: Resource }) {
  const query = useQueryClient(); const helpful = useMutation({ mutationFn: () => apiRequest(`/academic/resources/${resource.id}/helpful`, { method: "POST" }), onSuccess: () => void query.invalidateQueries({ queryKey: ["resources"] }) });
  return <Card className={styles.cardContent}><div className={styles.titleRow}><div><span className={styles.badge}>{resource.type.replaceAll("_", " ")}</span><h2>{resource.title}</h2><div className={styles.meta}>{resource.courseCode || "Campus resource"} · {resource.department?.name || "All departments"} · {dateLabel(resource.createdAt)}</div></div><BookOpen color="var(--accent)" /></div>{resource.description && <p>{resource.description}</p>}<div className={styles.actions}>{resource.fileUrl && <Button variant="secondary" onClick={() => window.open(resource.fileUrl, "_blank", "noopener,noreferrer")}><Download size={17} />Preview / Download</Button>}{resource.externalLink && <Button variant="secondary" onClick={() => window.open(resource.externalLink, "_blank", "noopener,noreferrer")}><ExternalLink size={17} />Open resource</Button>}<Button variant="ghost" onClick={() => helpful.mutate()}><ThumbsUp size={17} />Helpful {resource.helpfulCount || 0}</Button><EntityActions kind="resource" id={resource.id} saved={resource.saved} invalidate={["resources"]} /></div></Card>;
}

function ResourceDialog({ open, onClose }: { open: boolean; onClose(): void }) {
  const [form, setForm] = useState({ title: "", description: "", type: "NOTE", departmentId: "", courseCode: "", externalLink: "" }); const [file, setFile] = useState<File | null>(null); const cache = useQueryClient(); const { notify } = useToast();
  const create = useMutation({ mutationFn: () => { const body = new FormData(); Object.entries(form).forEach(([k,v]) => v && body.append(k, v)); if (file) body.append("pdf", file); return apiRequest("/academic/resources", { method: "POST", body }); }, onSuccess: () => { notify("Resource shared."); void cache.invalidateQueries({ queryKey: ["resources"] }); onClose(); } });
  return <Dialog title="Share resource" open={open} onClose={onClose}><form className={styles.form} onSubmit={e => { e.preventDefault(); create.mutate(); }}><Field label="Resource title"><Input required value={form.title} onChange={e => setForm(v => ({...v,title:e.target.value}))} /></Field><div className={styles.formGrid}><Field label="Resource type"><Select value={form.type} onChange={e => setForm(v => ({...v,type:e.target.value}))}>{types.filter(x => x !== "All").map(x => <option key={x}>{x}</option>)}</Select></Field><Field label="Department ID"><Input required inputMode="numeric" value={form.departmentId} onChange={e => setForm(v => ({...v,departmentId:e.target.value}))} /></Field><Field label="Course code"><Input value={form.courseCode} onChange={e => setForm(v => ({...v,courseCode:e.target.value}))} /></Field><Field label="External link"><Input type="url" value={form.externalLink} onChange={e => setForm(v => ({...v,externalLink:e.target.value}))} /></Field></div><Field label="Description"><Textarea value={form.description} onChange={e => setForm(v => ({...v,description:e.target.value}))} /></Field><label className={styles.file}>PDF or file<input type="file" accept=".pdf,.doc,.docx,.ppt,.pptx,image/*" onChange={e => setFile(e.target.files?.[0] || null)} /></label>{create.isError && <p role="alert" style={{color:"var(--danger)"}}>{create.error.message}</p>}<DialogActions><Button variant="secondary" onClick={onClose}>Cancel</Button><Button type="submit" disabled={create.isPending || !form.title || !form.departmentId || (!file && !form.externalLink)}>{create.isPending ? "Sharing…" : "Share resource"}</Button></DialogActions></form></Dialog>;
}
